server:
  port: 8899
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jumprun.c1jd2vehtfcz.eu-north-1.rds.amazonaws.com?serverTimezone=Asia/Seoul:3306/jumprun
    username: rnldyal7
    password: Tkddydrnldyal7
  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
